import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Montserrat } from 'next/font/google'
import { Poppins } from 'next/font/google'
import Nav from "@/components/General/Nav";

const font = Poppins({ subsets: ['latin'], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} min-h-screen`}
      >
        <Nav />
        <div className="h-[calc(100vh-152px)] overflow-y-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
